config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # get "restaurants", to: "restaurants#index", as: :restaurants

  # get "restaurants/new", to: "restaurants#new", as: :new_restaurant
  # post "restaurants", to: "restaurants#create"

  # get "restaurants/:id", to: "restaurants#show", as: :restaurant

  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews, dependent: :destroy

    CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
    validates :name, presence: true
    validates :address, presence: true
    validates :phone_number, presence: true
    validates :category, presence: true
    validates :category, inclusion: { in: CATEGORIES }


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  RATINGS = [0, 1, 2, 3, 4, 5]
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: RATINGS }
  validates :rating, numericality: { only_integer: true}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    def index
        @restaurants = Restaurant.all
    end    

    def new
        @restaurant = Restaurant.new 
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)
        @restaurant.save

        redirect_to restaurant_path(@restaurant)
    end

    def show
    @restaurant = Restaurant.find(params[:id])
    end    




    # def edit
    #     @restaurant = Restaurant.find(params[:id])
    # end

    # def update
    #     @restaurant = Restaurant.find(params[:id])
    #     @restaurant.update(restaurant_params)

    #     redirect_to restaurant_path(@restaurant)
    # end

    # def destroy
    #     @restaurant = Restaurant.find(params[:id])
    #     @restaurant.destroy
    
    #     redirect_to restaurants_path
    # end

    private

    def restaurant_params
        params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        # we need @restaurant in our `simple_form_for`
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review = Review.new
      end

    def create
        @review = Review.new(review_params)
        # we need `restaurant_id` to associate review with corresponding restaurant
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review.restaurant = @restaurant
        @review.save
        redirect_to restaurant_path(@restaurant)
    end

    private

    def review_params
        params.require(:review).permit(:content, :rating)
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <!-- [...] -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
    <h1>Restaurants</h1>
    <%= link_to "Add" , new_restaurant_path %>
  </div>
  <% @restaurants.each do |restaurant| %>
    <p><%= link_to restaurant.name, restaurant_path(restaurant),　class: "btn btn-primary" %></p>
    <%#= link_to  %>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<%= form_for(@restaurant) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :address %>
    <%= f.text_field :address %>
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
    <%= f.label :category %>
    <%= f.text_field :category %>
    <%= f.submit %>
  <% end %>

app/views/restaurants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @restaurant.phone_number %>
</p>

<p>
  <strong>Category:</strong>
  <%= @restaurant.category %>
</p>

<% if @restaurant.reviews.any? %>
  <p>
    <strong>Reviews:</strong>
    <ul>
      <% @restaurant.reviews.each do |review| %>
        <li class="list-group-item"><%= review.content%> | Rating: <%= review.rating%></li>
      <% end %>
    </ul>
  </p>
<% else %>
  <p>No reviews</p>
<% end %>
<%= link_to 'Add Review', new_restaurant_review_path(@restaurant), class: "btn btn-light" %>
<%= link_to 'Back', restaurants_path %>





app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
    <%= f.label :content %>
    <%= f.input :content %>
    <%= f.label :rating %>
    <%= f.number_field :rating %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>

<% end %>